export default [
  {
    mainIcon: require('./assets/spaceships/AnIn-1300 Vaisseau leger.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Targets.png'),
      require('./assets/items/Afterburners.png'),
    ],
    name: 'AnIn-1300 Light Transport',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Vega',
    price: 1748,
    bedrooms: 2,
    baths: 1,
    category: 'Raider',
  },
  {
    mainIcon: require('./assets/spaceships/GC-1 Tempete Fusion.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Targets.png'),
    ],
    name: 'GC-1 Tempete Fusion',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Antares',
    price: 21407,
    bedrooms: 4,
    baths: 2,
    category: 'Storm',
  },
  {
    mainIcon: require('./assets/spaceships/AnIn-T40 Armure Lourde.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Droids.png'),
    ],
    name: ' AnIn-T40 Heavy Armor',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Gemini',
    price: 3763,
    bedrooms: 3,
    baths: 2,
    category: 'Tank',
  },
  {
    mainIcon: require('./assets/spaceships/vso conquete.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Droids.png'),
      require('./assets/items/Protectors.png'),
      require('./assets/items/Repair Fields.png'),
    ],
    name: 'Vega Conquest Ship',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Mizar',
    price: 6237,
    bedrooms: 1,
    baths: 2,
    category: 'Clan',
  },
  {
    mainIcon: require('./assets/spaceships/AnIn-2000 Ingenieur Leger.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Droids.png'),
      require('./assets/items/Protectors.png'),
    ],
    name: 'AnIn-2000 Light Engineer',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Sol',
    price: 445,
    bedrooms: 2,
    baths: 1,
    category: 'Engineer',
  },
  {
    mainIcon: require('./assets/spaceships/AnIn-2000 Vitesse Etourdissante.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Droids.png'),
      require('./assets/items/Protectors.png'),
      require('./assets/items/Repair Fields.png'),
      require('./assets/items/Stun Charges.png'),
    ],
    name: 'AnIn-2000 Speed Stun',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Draconis',
    price: 445,
    bedrooms: 5,
    baths: 3,
    category: 'Shock',
  },
  {
    mainIcon: require('./assets/spaceships/mutilateur.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Droids.png'),
      require('./assets/items/Protectors.png'),
      require('./assets/items/Repair Fields.png'),
      require('./assets/items/Stun Charges.png'),
      require('./assets/items/Sticky Bombs.png'),
    ],
    name: 'HyAn Mutilator Parsec',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Sirius',
    price: 675400,
    bedrooms: 6,
    baths: 5,
    category: 'Defender',
  },
  {
    mainIcon: require('./assets/spaceships/disrupteur.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Droids.png'),
      require('./assets/items/Protectors.png'),
      require('./assets/items/Repair Fields.png'),
      require('./assets/items/Stun Charges.png'),
      require('./assets/items/Sticky Bombs.png'),
    ],
    name: 'AnIn-S78 Disruptor',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Tau Ceti',
    price: 675400,
    bedrooms: 6,
    baths: 5,
    category: 'Sniper',
  },
  {
    mainIcon: require('./assets/spaceships/RC-X-01 Griffe.png'),
    itemsIcons: [
      require('./assets/items/Blasters.png'),
      require('./assets/items/Collectors.png'),
      require('./assets/items/Repair Droids.png'),
      require('./assets/items/Repair Fields.png'),
      require('./assets/items/Afterburners.png'),
      require('./assets/items/Perforators.png'),
      require('./assets/items/Taunts.png'),
    ],
    name: 'RC-X-01 Claw',
    nameIcon: require('./assets/items/Afterburners.png'),
    system: 'Draconis',
    price: 8526,
    bedrooms: 3,
    baths: 2,
    category: 'Hybrid',
  },
];